name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then REQ=requirements.txt; else REQ=mc_test_app/requirements.txt; fi
          echo "Using requirements file: $REQ"
          pip install -r "$REQ" --no-cache-dir
      - name: Run tests
        run: |
          if [ -d tests ]; then TEST_DIR=tests; else TEST_DIR=mc_test_app/tests; fi
          echo "Running tests in $TEST_DIR"
          pytest -q "$TEST_DIR"

# Schlanke Variante: ein Job, nur bei Änderungen unter mc_test_app/.
