name: CI

on:
  push:
    branches: [ main ]
    paths:
      - 'mc_test_app/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'mc_test_app/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r mc_test_app/requirements.txt --no-cache-dir
      - name: Run tests
        run: pytest -q mc_test_app/tests

# Schlanke Variante: ein Job, nur bei Änderungen unter mc_test_app/.
