name: Deploy (manual)

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install minimal deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --no-cache-dir
      - name: Run tests
        run: |
          pytest -q
      - name: Subtree deploy to main
        run: |
          bash deploy.sh github
